name: Test

on:
  merge_group:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      trace:
        description: 'Turn on shell script debugging'
        type: boolean

defaults:
  run:
    shell: bash -x {0}

jobs:
  # test:
  #   runs-on: ubuntu-24.04
  #   timeout-minutes: 5
  #   if: github.repository == 'mhucka/teststuff'
  #   env:
  #     # The next var is used by Bash. We add 'xtrace' to the options if this run
  #     # is a workflow_dispatch invocation and the user set the 'trace' option.
  #     SHELLOPTS: 'xtrace'
  #   steps:
  #     - run: echo yes

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      SHELLOPTS: 'xtrace'
      foo: macos-15
    steps:
      - run: echo ${{fromJSON(env.foo)}}
