name: Test

on:
  merge_group:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      trace:
        description: 'Turn on shell script debugging'
        type: boolean

defaults:
  run:
    shell: bash -x {0}

jobs:
  # test:
  #   runs-on: ubuntu-24.04
  #   timeout-minutes: 5
  #   if: github.repository == 'mhucka/teststuff'
  #   env:
  #     # The next var is used by Bash. We add 'xtrace' to the options if this run
  #     # is a workflow_dispatch invocation and the user set the 'trace' option.
  #     SHELLOPTS: 'xtrace'
  #   steps:
  #     - run: echo yes

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        conf: [
          {os: macos-14, wh: macosx, arch: x86_64, py: 10, pyarch: x64},
          {os: ubuntu-24.04, wh: manylinux, arch: x86_64, py: 10, pyarch: x64},
 #         {os: windows-2019, wh: win, arch: AMD64,  py: 10, pyarch: x64},
        ]
    env:
      CIBW_ARCHS: ${{matrix.conf.arch}}
      CIBW_BUILD: cp3${{matrix.conf.py}}-${{matrix.conf.wh}}_${{matrix.conf.arch}}
#      CIBW_ENVIRONMENT: 'MACOSX_DEPLOYMENT_TARGET=${{matrix.conf.dep}}'
    steps:
      - if: startsWith(matrix.conf.os, 'macos')
        run: |
          os=${{matrix.conf.os}}
          echo MACOSX_DEPLOYMENT_TARGET=${os: -2} >> "$GITHUB_ENV"

      - run: echo "$MACOSX_DEPLOYMENT_TARGET"
