name: Test

on:
  merge_group:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash -x {0}

jobs:
  setup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - run: ls
